services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: aulas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"